task 0

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -6,10 +6,21 @@ if [ "$#" -ne 4 ]; then
 	exit 1
 fi
 
-
 PATH_TO_FILE="$1"
 IP="$2"
 USERNAME="$3"
 PATH_TO_SSH_KEY="$4"
 
+if [ ! -f "$PATH_TO_FILE" ]; then
+    echo "Error: File '$PATH_TO_FILE' does not exist."
+    exit 1
+fi
+
 scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@IP" ~/
+
+
+if [ $? -eq 0 ]; then
+    echo "File '$PATH_TO_FILE' successfully transferred to $USERNAME@$IP:~/"
+else
+    echo "Error: Failed to transfer file."
+fi
